apiVersion: v1
data:
  server-tokens: "false"
  ssl-ciphers: "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4"
  ssl-dh-param: "kube-system/lb-dhparam"
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf